version: '3.7'

services: 
  family-network-ui:
    image: family-network-ui:dev
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - 3001:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true